remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: EMER Convention 2024
description: Information about EMER SA Convetion organised by Slovak SA fellowship
show_downloads: false
logo: "assets/img/Sexaholics_Anonymous_Logo.jpg"
